# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: douyin.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64ouyin.proto\"\x82\x01\n\x0bPayloadInIm\x12\x14\n\x0c\x43ompressType\x18\x02 \x01(\x05\x12,\n\x08Payloads\x18\x01 \x03(\x0b\x32\x1a.PayloadInIm.PayloadsEntry\x1a/\n\rPayloadsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x9d\x01\n\tPushFrame\x12\r\n\x05SeqID\x18\x01 \x01(\x04\x12\r\n\x05LogID\x18\x02 \x01(\x04\x12\x0f\n\x07service\x18\x03 \x01(\x05\x12\x0e\n\x06method\x18\x04 \x01(\x05\x12\x18\n\x10payload_encoding\x18\x06 \x01(\t\x12\x14\n\x0cpayload_type\x18\x07 \x01(\t\x12\x0f\n\x07payload\x18\x08 \x01(\x0c\x12\x10\n\x08LodIDNew\x18\t \x01(\t\"\x89\x02\n\x07Message\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x0e\n\x06msg_id\x18\x03 \x01(\x03\x12\x10\n\x08msg_type\x18\x04 \x01(\x05\x12\x0e\n\x06offset\x18\x05 \x01(\x03\x12\x17\n\x0fneed_wrds_store\x18\x06 \x01(\x08\x12\x14\n\x0cwrds_version\x18\x07 \x01(\x03\x12\x14\n\x0cwrds_sub_key\x18\x08 \x01(\t\x12\x31\n\rmessage_extra\x18\t \x03(\x0b\x32\x1a.Message.MessageExtraEntry\x1a\x33\n\x11MessageExtraEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xf2\x02\n\x08Response\x12\x1a\n\x08messages\x18\x01 \x03(\x0b\x32\x08.Message\x12\x0e\n\x06\x63ursor\x18\x02 \x01(\t\x12\x16\n\x0e\x66\x65tch_interval\x18\x03 \x01(\x03\x12\x0b\n\x03now\x18\x04 \x01(\x03\x12\x14\n\x0cinternal_ext\x18\x05 \x01(\t\x12\x12\n\nfetch_type\x18\x07 \x01(\x05\x12\x30\n\x0croute_params\x18\x06 \x03(\x0b\x32\x1a.Response.RouteParamsEntry\x12\x1a\n\x12heartbeat_duration\x18\x08 \x01(\x03\x12\x10\n\x08need_ack\x18\t \x01(\x08\x12\x13\n\x0bpush_server\x18\n \x01(\t\x12\x13\n\x0blive_cursor\x18\x0b \x01(\t\x12\x17\n\x0fhistory_no_more\x18\x0c \x01(\x08\x12\x14\n\x0cproxy_server\x18\r \x01(\t\x1a\x32\n\x10RouteParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'douyin_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PAYLOADINIM_PAYLOADSENTRY']._options = None
  _globals['_PAYLOADINIM_PAYLOADSENTRY']._serialized_options = b'8\001'
  _globals['_MESSAGE_MESSAGEEXTRAENTRY']._options = None
  _globals['_MESSAGE_MESSAGEEXTRAENTRY']._serialized_options = b'8\001'
  _globals['_RESPONSE_ROUTEPARAMSENTRY']._options = None
  _globals['_RESPONSE_ROUTEPARAMSENTRY']._serialized_options = b'8\001'
  _globals['_PAYLOADINIM']._serialized_start=17
  _globals['_PAYLOADINIM']._serialized_end=147
  _globals['_PAYLOADINIM_PAYLOADSENTRY']._serialized_start=100
  _globals['_PAYLOADINIM_PAYLOADSENTRY']._serialized_end=147
  _globals['_PUSHFRAME']._serialized_start=150
  _globals['_PUSHFRAME']._serialized_end=307
  _globals['_MESSAGE']._serialized_start=310
  _globals['_MESSAGE']._serialized_end=575
  _globals['_MESSAGE_MESSAGEEXTRAENTRY']._serialized_start=524
  _globals['_MESSAGE_MESSAGEEXTRAENTRY']._serialized_end=575
  _globals['_RESPONSE']._serialized_start=578
  _globals['_RESPONSE']._serialized_end=948
  _globals['_RESPONSE_ROUTEPARAMSENTRY']._serialized_start=898
  _globals['_RESPONSE_ROUTEPARAMSENTRY']._serialized_end=948
# @@protoc_insertion_point(module_scope)
